# Generated by Django 6.0.7 on 2026-09-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
